name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Garantir permissões de gravação
        run: chmod -R 777 dist/

      - name: Gerar snake
        uses: Platane/snk@v3
        with:
          github_user_name: mthportes
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit arquivos
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 🐍 update snake contribution grid
          add: "dist/*.svg"

      - name: Publicar no branch
        run: |
          git fetch
          git switch -C output
          git restore --source=HEAD:dist dist
          git add dist
          git commit -m "Publish contribution grid snake"
          git push origin output --force
